CREATE TABLE `perfil_customer` (
  `ID_PERFIL` int(11) NOT NULL,
  `DESCRIPCION` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_PERFIL`)
)

go 

CREATE TABLE `category` (
  `ID_CATEGORIA` int(11) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `DESCRIPCION` varchar(100) NOT NULL,
  `RUTA` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`)
)

go

CREATE TABLE `estado_item` (
  `ID_ESTADO_ITEM` int(11) NOT NULL,
  `ESTADO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_ESTADO_ITEM`)
)

go

CREATE TABLE `customer` (
  `ID_CUSTOMER` int(11) NOT NULL,
  `ID_PERFIL` int(11) NOT NULL,
  `IDENTIFICACION` int(11) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `SEXO` varchar(100) NOT NULL,
  `DIRECCION` varchar(100) NOT NULL,
  `FNACIMIENTO` date NOT NULL,
  `TELEFONO` varchar(100) NOT NULL,
  PRIMARY KEY (`IDENTIFICACION`),
  KEY `ID_ESTADO_CUSTOMER` (`ID_PERFIL`),
  KEY `ID_PERFIL` (`ID_PERFIL`),
  KEY `IDENTIFICACION` (`IDENTIFICACION`),
  KEY `IDENTIFICACION_2` (`IDENTIFICACION`),
  CONSTRAINT `customer_ibfk_1` FOREIGN KEY (`ID_PERFIL`) REFERENCES `perfil_customer` (`ID_PERFIL`)
)

go


CREATE TABLE `item` (
  `ID_ITEM` int(11) NOT NULL,
  `PRODUCTO` varchar(100) NOT NULL,
  `IDENTIFICACION_CUSTOMER` int(11) NOT NULL,
  `ID_CATEGORIA` int(11) NOT NULL,
  `FECHA_DE_BAJA` datetime DEFAULT NULL,
  `ESTADO` int(11) NOT NULL,
  PRIMARY KEY (`ID_ITEM`),
  KEY `ID_CATEGORIA` (`ID_CATEGORIA`),
  KEY `ESTADO` (`ESTADO`),
  KEY `IDENTIFICACION` (`IDENTIFICACION_CUSTOMER`),
  CONSTRAINT `item_ibfk_2` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `category` (`ID_CATEGORIA`),
  CONSTRAINT `item_ibfk_3` FOREIGN KEY (`ESTADO`) REFERENCES `estado_item` (`ID_ESTADO_ITEM`),
  CONSTRAINT `item_ibfk_4` FOREIGN KEY (`IDENTIFICACION_CUSTOMER`) REFERENCES `customer` (`IDENTIFICACION`)
)


go


CREATE TABLE `orden` (
  `ID_ORDEN` int(11) NOT NULL AUTO_INCREMENT,
  `IDENTIFICACION_COMPRADOR` int(11) NOT NULL,
  `ID_ITEM` int(11) NOT NULL,
  `PRECIO` int(11) NOT NULL,
  `CANTIDAD` int(11) NOT NULL,
  `FVENTA` datetime NOT NULL,
  `IDENTIFICACION_VENDEDOR` int(11) NOT NULL,
  PRIMARY KEY (`ID_ORDEN`),
  KEY `IDENTIFICACION` (`IDENTIFICACION_COMPRADOR`),
  KEY `ID_CATEGORIA` (`ID_ITEM`),
  KEY `IDENTIFICACION_VENDEDOR` (`IDENTIFICACION_VENDEDOR`),
  CONSTRAINT `orden_ibfk_3` FOREIGN KEY (`IDENTIFICACION_COMPRADOR`) REFERENCES `customer` (`IDENTIFICACION`),
  CONSTRAINT `orden_ibfk_4` FOREIGN KEY (`ID_ITEM`) REFERENCES `item` (`ID_ITEM`),
  CONSTRAINT `orden_ibfk_5` FOREIGN KEY (`IDENTIFICACION_VENDEDOR`) REFERENCES `item` (`IDENTIFICACION_CUSTOMER`)
)
